### ISSUE TITLE
Support for Promises as Monads

### ISSUE THREAD

**Issue by sebasgarcep** [cwmyers/monet.js#38]
This would be a nice feature to include into the library at some point. Promises are great, but what I'm not sure is if they completely follow monadic laws

**Comment by cwmyers** [comment]
I'm working on Promises/Futures at the moment.  Stay tuned!

**Comment by mostr** [comment]
Hey @cwmyers, are there any plans to ship support for promises/futures any time soon? Thanks

**Comment by alem0lars-yoroi** [comment]
Are there any news for supporting native node Promises as monads?

**Comment by ulfryk** [comment]
@alem0lars-yoroi  - what do yo mean by `native node Promises as monads` ?

I am a fan of adding monadic Futures (rather than Promises - to avoid name conflicts). And to do it with next milestone (0.10.0) as current milestone is mostly cleanup, bugfixes and limited extending of current API.

WDYT @cwmyers

**Comment by sebasgarcep** [comment]
@ulfryk I agree with you. We should stop calling it Promises and rather call it Futures.

**Comment by alem0lars-yoroi** [comment]
I also agree.

What I was going to figure out was if it was already planned some
interoperability between existing code using node's native Promises and
Futures.

**Comment by graingert** [comment]
FYI, here's the issue: https://github.com/monet/monet.js/issues/102
