### ISSUE TITLE
curry and map

### ISSUE THREAD

**Issue by k33g** [cwmyers/monet.js#55]
Hello, 

I'm trying this:

```javascript
var add = function(a,b) {
  return a+b;
}.curry();
var increment = add(1);
var arr1 = [100, 200, 300, 400, 500];
var arr2 = arr1.map(increment); 
```

I expect an array of Integer for `arr2` : `101,201,301,401,501` but I get an array of function instead

Then it's ok If I do this `arr2 = arr1.map((item)=>increment(item));`

Or this is ok
```javascript
var incr = function(x) { return x + 1; }
arr1.map(incr) // 101,201,301,401,501
```

what I missed (misunderstood) with curry?  

thx 😄

**Comment by ulfryk** [comment]
@k33g - I've checked implementation and it seems that there is a little bug.

This way should work:

```
…
var arr2 = arr1.map(funciton(n, i, arr) { return  increment(n); }); 
```

What you discovered happens because `.map` callback has 3 args and monet internally tests `args1.size() == fn.length` which will be in this case `3 == 1`

Will probably try to hotfix but you can now just fix it using curried function with strict arity :)

**Comment by k33g** [comment]
@ulfryk thx for the response, I really ❤️ Monet. It make me more comfortable with functional programming

**Comment by ulfryk** [comment]
Should be fixed with new release -> https://github.com/cwmyers/monet.js/releases/tag/v0.8.10

@k33g  - can you confirm ?

**Comment by k33g** [comment]
@ulfryk it works perfectly :)

**Comment by ulfryk** [comment]
Great! Closing this issue :)
