### ISSUE TITLE
Maybe.when?

### ISSUE THREAD

**Issue by emmanueltouzery** [cwmyers/monet.js#99]
would you accept a pull request adding:

    IMaybeStatic<T>.when(boolean, T|()=>T): Maybe<T>

so the second parameter is either a value, or a parameterless function returning the value. This does come in often. Not *that* often, but it does.

    Maybe.when(true, 5) => Some<5>

**Comment by ulfryk** [comment]
You mean as a shortcut for one of these:
- `(cond: boolean, x: T) => Some(x).filter(() => cond)`
- `(cond: boolean, x: T) => Maybe.fromNull(x).filter(() => cond)`
:grey_question: 

I see few issues here:
1. We can't overload second param because someone may need a `Maybe<(x: X) => Y>`
   - this can be fixed with creating 2 constructors:
     - `.when<T>(cond: boolean, value: T): Maybe<T>`
     - `.whenLazy<T>(cond: boolean, fn: () => T): Maybe<T>`
   - or by curried API:
     - `.when(cond)(val)` vs `.when(cond).lazy(() => val)`
2. _When_ is a common constructor used in `Promise` libs (it may be misunderstood):
   - `PromiseStatic.when<T>(inp: T | Promise<T>): Promise<T>`

I think that there is simpler solution - we can add new filtering method which takes a `boolean` instead of `() => boolean` like `.filterWith(cond: boolean)`, does it make sense for you, or is it not enough ? Or is laziness the core feature ?

**Comment by emmanueltouzery** [comment]
interesting points. laziness was not the core feature I had in mind. It's true that `Some.filter` (which I didn't think about) is ALMOST there but the extra function inside may be the drop that makes it a little less readable than it could be. So your `filterWith` is attractive.
Then there's the question of the name. `filter` has the obvious parallel, and the same signature than with collections. `filterWith` stretches the analogy. Maybe a name containing `if` or `when` would be better. But I can't think a particularly good one right now.

so, if you think `filterWith` is worth adding to monet, I can code the PR, and then I would use it in my code :-)

**Comment by ulfryk** [comment]
I believe that it's worth adding. But you are absolutely right that `filterWith` is not the best name ;) Standalone `if` and `when` also have some downsides. Here are my propositions:

- `toNoneIf(c: Boolean)` with alias: `toNothingIf`
- `toNoneWhen` ( + `toNothingWhen` )
- `dropIf`
- `toNone(c = true)` (so condition defaults to `false`)
- **`orNoneIf`** ( + `orNothingIf`) <-- this one is my favourite
- `orNoneWhen` ( + `orNothingWhen` )

WDYT @emmanueltouzery  ?

**Comment by emmanueltouzery** [comment]
I'll think more, but a quick thought now.. What about `exceptIf`?

**Comment by emmanueltouzery** [comment]
That's the reverse boolean of the one i first mentionned though, but maybe it doesn't matter.

**Comment by ulfryk** [comment]
@emmanueltouzery - sorry, I was thinking about `exceptIf` and also about best name for **NOT REVERSED** version, but it somehow left my head :( Anyway thanks for publishing PR -- I think that it's OK that way :)
